// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzhlxeyel19rM3wtT93pucCANSE4BmdnA',
    appId: '1:910848965227:web:f04d00f18d487de7154f2e',
    messagingSenderId: '910848965227',
    projectId: 'sova-f46d9',
    authDomain: 'sova-f46d9.firebaseapp.com',
    storageBucket: 'sova-f46d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SCUNZj4031iRYqcsJ4E3RX-BMC0sxvw',
    appId: '1:910848965227:android:7cc0fd7bdb93109e154f2e',
    messagingSenderId: '910848965227',
    projectId: 'sova-f46d9',
    storageBucket: 'sova-f46d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAkJqbxz56OATcusYVbX-eXhFBKoiOjM',
    appId: '1:910848965227:ios:45a8ffe7c90b7356154f2e',
    messagingSenderId: '910848965227',
    projectId: 'sova-f46d9',
    storageBucket: 'sova-f46d9.appspot.com',
    iosClientId: '910848965227-6cantfhm0laq6v051r2n3tp81f7kit7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAkJqbxz56OATcusYVbX-eXhFBKoiOjM',
    appId: '1:910848965227:ios:45a8ffe7c90b7356154f2e',
    messagingSenderId: '910848965227',
    projectId: 'sova-f46d9',
    storageBucket: 'sova-f46d9.appspot.com',
    iosClientId: '910848965227-6cantfhm0laq6v051r2n3tp81f7kit7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sova',
  );
}
